Cool-Cars/Cool-Cars.com

package-lock.json
package.json
src/App.jsx

Added a button to main page to show how you can import and use Material UI components.

added minimal example of material ui as button on main page.

---

package-lock.json
package.json
src/jestExample.js
src/tests/jestExample.test.js

Installed jest and added a minor example of how to use and folder structure.

installed jest 

---

database.js
package-lock.json
package.json
server.js

added sql connection file and exported to express server

added sql connection file and exported to express server

---

main.sql

added the tables to the database

---

database/database.js
database/dbSetup.js

cleaning up database file. We may or may not want to use that function later so saving it in it's own file for now.

moved database setup function from database.js to dbSetup.js 

---

database/populate.sql

added 10 new entries to populate.sql

---

server.js
src/components/CarCard.jsx

I didn't realize that I had already made a PR for the major changes on this branch.

tiny bit of cleanup

---

src/components/NavBar.jsx

added admin page nav option for admins only

added admin page nav option for admins only

---

database/main.sql

updated create user table

---

database/populate.sql
vite.config.js

took off id in sql insert file and fixed vite config to allow to[p level await

changed vite config to allow top level await

---

src/Landing.css
src/Login.jsx
src/components/DropdownMenu.jsx
src/components/NavBar.css
src/components/NavBar.jsx
src/index.css

Login, Register, Admin page and logout are now all located in a dropdown that is opened by clicking on the user avatar icon.
A logged in user with role user will only see a logout option
A logged in user with role admin will see the admin page and logout options
All logged in users will see the Welcome, user string
A logged out user will see options for login and register
Other changes:
* side scoll bar was showing on the landing page, now it is not
* removed login alert 
* updated fonts and colors in the navbar
* removed car icon from navbar, I didn't think it looked good after the landing page glow up. (can add back if yall disagree)

Navbar Updates mostly related to login logout

---

src/AboutUs/AboutUs.css
src/AboutUs/AboutUs.jsx
src/AboutUs/HeaderSection.jsx
src/Register.jsx
src/index.css
src/main.jsx

removed import for index.css and added a few styling changes for the aboutUs page to look good on smaller devices.

made aboutUs page responsive

---

database/populate.sql
src/AboutUs/AboutUs.jsx
src/InventoryPage.jsx
src/Landing.jsx

Added functionality to the view all inventory button and the view by vehicle type buttons.
Still need to update the filters on the inventory page. Goal is to have the checkbox auto checked when you search by vehicle type from the landing page. will work on this next.

Landing page functionality

---

package-lock.json
package.json
server.js
src/AddCar.jsx
src/InventoryPage.jsx

Tweaked the post request.
Changed styling.
Removed old MUI dependency. (thanks Noah)

Add a car finished.

---

package-lock.json
src/AboutUs/AboutUs.css
src/AboutUs/AboutUs.jsx
src/AboutUs/HeaderSection.jsx
src/theme.jsx

added theme for font family

---

server.js
src/InventoryPage.jsx
src/Login.jsx
src/Wishlist.jsx
src/components/CarCard.jsx
src/components/CarCard.test.js
src/contexts/FavoritesContext.jsx
src/main.jsx

inventory page and wishlist should now display accurate user favorites. 
updated to set favorites context upon login.

Wishlist bug fixes

---

src/AboutUs/AboutUs.css
src/AboutUs/FilterReviews.jsx
src/AboutUs/NotRefactored.jsx

finishing touches

---

src/InventoryPage.jsx
src/components/CarCard.jsx

Finished sorting and filtering functionality.

Finish inventory

---

package-lock.json
package.json
server.js
src/AdminPage.jsx
src/InventoryPage.jsx
src/components/AdminHeader.jsx
src/components/CarCard.jsx

Images are reliable, wishlist only works with user id = 2 for some reason. Still need to do responsiveness and maybe chatGPT integration?

Admin page delete and inventory page cleaned up.

---

database/main.sql
database/populate.sql
package-lock.json
package.json
server.js
src/components/CarCard.jsx
src/components/DropdownMenu.jsx

You have to wipe db again, sorry.
Then create it again.
Then run main.sql.
Then run populate.sql.
Wishlist still not working for user id 1.
Ask for openAI api key when I wake up to add it to your .env

Ai description functionality done
